<a href="https://colab.research.google.com/github/ttsuneoka/GoogleColab/blob/master/Chapter2_1_2_2_191104.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline
%precision 3

'%.3f'

In [ ]:
# Create a matrix
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])
data

array([ 9,  2,  3,  4, 10,  6,  7,  8,  1,  5])

In [ ]:
data.dtype

dtype('int64')

In [ ]:
type(data)

numpy.ndarray

In [ ]:
data.ndim

1

In [ ]:
data.size

10

In [ ]:
data * 2

array([18,  4,  6,  8, 20, 12, 14, 16,  2, 10])

In [ ]:
print(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) * np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))
print(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) ** 2)
print(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) / np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

[10 18 24 28 30 30 28 24 18 10]
[  1   4   9  16  25  36  49  64  81 100]
[ 0.1    0.222  0.375  0.571  0.833  1.2    1.75   2.667  4.5   10.   ]


In [ ]:
print(data)
data.sort()
print(data)

[ 9  2  3  4 10  6  7  8  1  5]
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
data[::-1].sort()

In [ ]:
print(data)

[10  9  8  7  6  5  4  3  2  1]


In [ ]:
print(data.min())
print(data.max())
print(data.sum())
print(data.cumsum())
print(data.cumsum()/data.sum())

1
10
55
[10 19 27 34 40 45 49 52 54 55]
[0.182 0.345 0.491 0.618 0.727 0.818 0.891 0.945 0.982 1.   ]


In [ ]:
import numpy.random as random

In [ ]:
random.seed(0)

rnd_data = random.randn(10)
print(rnd_data)

[ 1.764  0.4    0.979  2.241  1.868 -0.977  0.95  -0.151 -0.103  0.411]


In [ ]:
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])

print(random.choice(data, 10))
print(random.choice(data, 10, replace=False))

[ 7  8  8  1  2  6  5  1  5 10]
[10  2  7  8  3  1  6  5  9  4]


In [ ]:
N = 10 ** 6

normal_data = [random.random() for _ in range(N)]

numpy_random_data = np.array(normal_data)

%timeit sum(normal_data)

%timeit np.sum(numpy_random_data)

100 loops, best of 3: 5.75 ms per loop
1000 loops, best of 3: 356 µs per loop


In [ ]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
array1 = np.arange(9).reshape(3,3)
print(array1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
array1[0,:]

array([0, 1, 2])

In [ ]:
array1[:,0]

array([0, 3, 6])

In [ ]:
array2 = np.arange(9, 18).reshape(3,3)
print(array2)

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [ ]:
np.dot(array1, array2)

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [ ]:
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
array1 * array2

array([[  0,  10,  22],
       [ 36,  52,  70],
       [ 90, 112, 136]])

In [ ]:
print(np.zeros((2,3),dtype=np.int64))

[[0 0 0]
 [0 0 0]]


In [ ]:
print(np.ones((2,3),dtype=np.int64))

[[1 1 1]
 [1 1 1]]


In [ ]:
x = np.arange(1, 51)
print(np.sum(x))

1275


In [ ]:
random.seed(0)
x = random.randn(10)
print(x)
print(np.min(x))
print(np.max(x))
print(np.sum(x))

[ 1.764  0.4    0.979  2.241  1.868 -0.977  0.95  -0.151 -0.103  0.411]
-0.977277879876411
2.240893199201458
7.380231707288347


In [ ]:
a = 3 * np.ones((5,5),dtype=np.float64)
print(a.dot(a))

[[45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]]
