<a href="https://colab.research.google.com/github/ttsuneoka/GoogleColab/blob/master/Chapter2_3_191106.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import scipy as sp
import scipy.linalg as linalg
from scipy.optimize import minimize_scalar
import numpy as np

In [ ]:
matrix = np.array([[1, -1, -1], [-1, 1, -1], [-1, -1, 1]])
print(matrix)

[[ 1 -1 -1]
 [-1  1 -1]
 [-1 -1  1]]


In [ ]:
#行列式
print("行列式")
print(linalg.det(matrix))

行列式
-4.0


In [ ]:
#逆行列
print("逆行列")
print(linalg.inv(matrix))

逆行列
[[ 0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]


In [ ]:
print(matrix.dot(linalg.inv(matrix)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
eig_value, eig_vector = linalg.eig(matrix)

In [ ]:
print("固有値")
print(eig_value)
print("固有ベクトル")
print(eig_vector)

固有値
[-1.+0.j  2.+0.j  2.+0.j]
固有ベクトル
[[ 0.57735027  0.81649658  0.40824829]
 [ 0.57735027 -0.40824829 -0.81649658]
 [ 0.57735027 -0.40824829  0.40824829]]


In [ ]:
linalg.eigvals(matrix)

array([-1.+0.j,  2.+0.j,  2.+0.j])

In [ ]:
eig_value1, eig_vector1 = linalg.eigh(matrix)
print(eig_value1)
print(eig_vector1)

[-1.  2.  2.]
[[-0.57735027  0.          0.81649658]
 [-0.57735027 -0.70710678 -0.40824829]
 [-0.57735027  0.70710678 -0.40824829]]


In [ ]:
matrix1 = np.array([[1,1,0],[1,2,1],[2,5,3]])
print(matrix1)

[[1 1 0]
 [1 2 1]
 [2 5 3]]


In [ ]:
eig_value, eig_vector = linalg.eig(matrix1)
print("固有値")
print(eig_value)
print("固有ベクトル")
print(eig_vector)

固有値
[ 5.00000000e+00+0.j  1.00000000e+00+0.j -4.34391006e-16+0.j]
固有ベクトル
[[ 8.51256531e-02  7.07106781e-01  5.77350269e-01]
 [ 3.40502612e-01  3.54627176e-16 -5.77350269e-01]
 [ 9.36382184e-01 -7.07106781e-01  5.77350269e-01]]


In [ ]:
eig_value1, eig_vector1 = linalg.eigh(matrix1)
print(eig_value1)
print(eig_vector1)

[-2.63829155  0.46367063  8.17462092]
[[-0.18532935  0.9392985  -0.28874098]
 [-0.70167054 -0.33220368 -0.63031673]
 [ 0.68797637 -0.08578485 -0.72064518]]


In [ ]:
# Newton Method
from scipy.optimize import newton

def my_function(x):
    return (x**2-4*x+4)

print(newton(my_function,0))

1.9999999804639512


In [ ]:
# Brent Method
print(minimize_scalar(my_function, method='Brent'))

     fun: 0.0
    nfev: 9
     nit: 4
 success: True
       x: 2.0


In [ ]:
mat_A = np.array([[1,2,3],[1,3,2],[3,1,2]])
print(mat_A)

[[1 2 3]
 [1 3 2]
 [3 1 2]]


In [ ]:
det_mat_A = linalg.det(mat_A)
print(det_mat_A)

-12.0


In [ ]:
inv_mat_A = linalg.inv(mat_A)
print(inv_mat_A)

[[-0.33333333  0.08333333  0.41666667]
 [-0.33333333  0.58333333 -0.08333333]
 [ 0.66666667 -0.41666667 -0.08333333]]


In [ ]:
eig_value_mat_A, eig_vector_mat_A = linalg.eig(mat_A)
print(eig_value_mat_A)
print(eig_vector_mat_A)

[ 6.        +0.j -1.41421356+0.j  1.41421356+0.j]
[[-0.57735027 -0.72236645  0.16041816]
 [-0.57735027 -0.14290228 -0.81090869]
 [-0.57735027  0.67658381  0.56275492]]


In [ ]:
# Newton Method
from scipy.optimize import newton

def my_function(x):
    return (x**3+2*x+1)

print(newton(my_function,0))
print(my_function(newton(my_function,0)))

-0.45339765151640365
3.3306690738754696e-16
