<a href="https://colab.research.google.com/github/ttsuneoka/GoogleColab/blob/master/Chapter6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

hier_df = DataFrame(
    np.arange(9).reshape((3,3)),
    index = [
        ['a', 'a', 'b'],
        [1, 2, 2]],
    columns = [
        ['Osaka', 'Tokyo', 'Osaka'],
        ['Blue', 'Red', 'Red']
    ]
)

print(hier_df)

    Osaka Tokyo Osaka
     Blue   Red   Red
a 1     0     1     2
  2     3     4     5
b 2     6     7     8


In [ ]:
hier_df.index.names = ['key1', 'key2']
hier_df.columns.names = ['city', 'color']

print(hier_df)

city      Osaka Tokyo Osaka
color      Blue   Red   Red
key1 key2                  
a    1        0     1     2
     2        3     4     5
b    2        6     7     8


In [ ]:
print(hier_df['Osaka'])

color      Blue  Red
key1 key2           
a    1        0    2
     2        3    5
b    2        6    8


In [ ]:
hier_df.sum(level='key2', axis=0)

city  Osaka Tokyo Osaka
color  Blue   Red   Red
key2                   
1         0     1     2
2         9    11    13

In [ ]:
hier_df.sum(level='color',axis=1)

color      Blue  Red
key1 key2           
a    1        0    3
     2        3    9
b    2        6   15

In [ ]:
hier_df.sum(level='city',axis=1)

city       Osaka  Tokyo
key1 key2              
a    1         2      1
     2         8      4
b    2        14      7

In [ ]:
hier_df.sum(level='key1',axis=0)

city  Osaka Tokyo Osaka
color  Blue   Red   Red
key1                   
a         3     5     7
b         6     7     8

In [ ]:
hier_df.drop(['b'])

city      Osaka Tokyo Osaka
color      Blue   Red   Red
key1 key2                  
a    1        0     1     2
     2        3     4     5

In [ ]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
hier_df1 = DataFrame(
    np.arange(12).reshape(3,4),
    index = [['c', 'd', 'e'], [1,2,1]],
    columns = [
        ['Kyoto', 'Nagoya', 'Hokkaido', 'Kyoto'],
        ['Yellow', 'Yellow', 'Red', 'Blue']
    ]
)

hier_df1.index.names = ['key1', 'key2']
hier_df1.columns.names = ['city', 'color']
print(hier_df1)

city       Kyoto Nagoya Hokkaido Kyoto
color     Yellow Yellow      Red  Blue
key1 key2                             
c    1         0      1        2     3
d    2         4      5        6     7
e    1         8      9       10    11


In [ ]:
hier_df1['Kyoto']

color      Yellow  Blue
key1 key2              
c    1          0     3
d    2          4     7
e    1          8    11

In [ ]:
hier_df1.mean(level='city', axis=1)

city       Kyoto  Nagoya  Hokkaido
key1 key2                         
c    1       1.5     1.0       2.0
d    2       5.5     5.0       6.0
e    1       9.5     9.0      10.0

In [ ]:
hier_df1.sum(level='key2', axis=0)

city   Kyoto Nagoya Hokkaido Kyoto
color Yellow Yellow      Red  Blue
key2                              
1          8     10       12    14
2          4      5        6     7