<a href="https://colab.research.google.com/github/ttsuneoka/GoogleColab/blob/master/Pytorch_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import torch

In [ ]:
t = torch.tensor([[1, 2], [3, 4]])
print(t)

tensor([[1, 2],
        [3, 4]])


In [ ]:
t = torch.tensor([[1, 2], [3, 4]], dtype=torch.float64)
print(t)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [ ]:
t = torch.arange(0, 10)
print(t)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
t = torch.zeros(100, 10)
print(t)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],


In [ ]:
t = torch.randn(100, 10)
print(t)

tensor([[ 1.0125e+00, -1.3577e+00, -3.1008e-01,  1.1428e+00,  2.6917e-01,
         -1.2529e-01, -6.7977e-01,  2.8544e-01,  1.1190e+00, -9.8864e-01],
        [-4.3942e-01,  1.2488e+00,  3.6446e-01, -4.8249e-01, -6.0347e-01,
          1.9443e-01, -1.1749e+00, -3.7477e-01, -1.0039e+00, -3.0223e-01],
        [-1.0510e-01, -1.8900e+00,  1.0646e+00, -4.0627e-01,  2.3456e-01,
          2.5173e-01, -1.0237e+00,  3.7217e-01,  3.3184e-01, -3.4834e-01],
        [ 1.0149e+00,  1.6369e+00, -1.4338e+00, -6.0027e-01, -1.8437e+00,
          7.5154e-01,  6.4346e-01, -1.9035e-01,  7.9173e-01, -1.3057e+00],
        [ 1.0072e+00, -4.9778e-01,  5.5231e-01,  4.7974e-01,  2.5638e-01,
          5.7173e-01,  1.0339e-01, -1.2511e+00,  1.2801e-01,  2.6520e+00],
        [ 1.0762e+00, -4.5530e-02, -3.1670e-01, -6.1497e-02,  2.8280e-01,
          5.1833e-01, -1.7448e+00, -1.1313e+00, -1.2997e+00, -5.5423e-01],
        [ 3.1807e-01, -1.6883e-01,  8.4234e-01,  6.7587e-01,  1.4636e+00,
         -1.8644e+00,  9.1193e-0

In [ ]:
print(t.size())

torch.Size([100, 10])


In [ ]:
t = torch.tensor([[1, 2], [3, 4]])
print(type(t))

x = t.numpy()
print(type(x))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>
